services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: web_server_sequential
    networks:
      web_network:
        ipv4_address: 54.99.52.17
    ports:
      - "80:80"
    restart: unless-stopped
    command: ["python3", "-u", "server/sequential_server.py"]

  server_concurrent:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: web_server_concurrent
    networks:
      web_network:
        ipv4_address: 54.99.52.18
    ports:
      - "8080:80"
    restart: unless-stopped
    command: ["python3", "-u", "server/concurrent_server.py"]

  client1:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: web_client_1
    networks:
      web_network:
        ipv4_address: 54.99.52.19
    depends_on:
      - server
    command: ["python3", "client.py"]

  client2:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: web_client_2
    networks:
      web_network:
        ipv4_address: 54.99.52.20
    depends_on:
      - server
    command: ["python3", "client.py"]

  client3:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: web_client_3
    networks:
      web_network:
        ipv4_address: 54.99.52.21
    depends_on:
      - server
    command: ["python3", "client.py"]

networks:
  web_network:
    driver: bridge
    ipam:
      config:
        - subnet: 54.99.52.0/24
